# Generated by Django 2.0.5 on 2018-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Document ', max_length=120),
        ),
        migrations.AddField(
            model_name='document',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
