# Generated by Django 2.0.5 on 2018-11-17 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0002_auto_20181117_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
