# Generated by Django 2.0.5 on 2018-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0003_auto_20181117_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/files'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='document ', max_length=120),
        ),
    ]
