# Generated by Django 2.0.5 on 2018-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0004_auto_20181118_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='pdfs/images'),
        ),
    ]
