# Generated by Django 2.0.5 on 2018-11-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0005_page_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='pdf',
            new_name='thumbnail',
        ),
    ]
