# Generated by Django 2.0.5 on 2018-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0010_auto_20181118_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['nr']},
        ),
    ]
