# Generated by Django 2.0.5 on 2018-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_Service', '0011_auto_20181128_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pdfs/thumbnails'),
        ),
    ]
